# Running this with gcloud builds submit . will run on your project using 
# the default Cloud Build service account.
steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform plan
    args:
      - '-c'
      - |
        terraform plan -var-file=terrform.tfvars
        
logsBucket: 'gs://tf-code-log'

